spring.application.name=Hackathon_IT211
spring.datasource.url=jdbc:mysql://localhost:3306/hackathon_it211
spring.datasource.username=root
spring.datasource.password=260106huy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true